---
title: "LOOCV"
author: "zhengfan"
date: "11/15/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

All result are based on the most recent run(NOV.14.2019).

# In sample

```{r message=FALSE}
library(rstan)
library(loo)
fit <- readRDS(file = "rdsoutput/qi1.rds")
stan.data <- readRDS(file = "output/stan.qi1.rds")
loo.fit <- loo(fit)
print(loo.fit)
plot(loo.fit)
```

# out of sample
```{r}

#sub_validationoutput.R
fit <- readRDS(file = "rdsoutput/qi1.loo.rds")
stan.data <- readRDS(file = "output/stan.qi1.loo.rds")

array <- extract(fit)
# indices of test set
getitest <- setdiff(seq(1,stan.data$N), stan.data$getitrain_k)

# errors
pred <- apply(array$prep,2,median)
errors <- stan.data$Y[getitest] - pred[getitest]
hist(errors)
# summarize
mean(errors)  
median(errors)  
mean(abs(errors))
median(abs(errors))


ntest <- length(getitest)
ntest
# PIT
pit.j <- rep(NA, ntest)
for (j in 1:ntest){
  i <- getitest[j]
  yrepi.s <- array$prep[,i]
  pit.j[j] <- mean(yrepi.s <= stan.data$Y[i])
} 
hist(pit.j, freq = F, xlab = "PIT-values", main = "Predicting last obs")  # should look uniform
abline(h=1)  

p <- 0.1
qbinom(c(0.1, 0.9), size = ntest, prob = p)/ntest # 80% PI for prop of left out obs in one bin of PIT values with range of p 
qbinom(c(0.25, 0.75), size = ntest, prob = p)/ntest # 50% PI for prop of left out obs in one bin of PIT values with range of p 
p <- 0.25
qbinom(c(0.1, 0.9), size = ntest, prob = p)/ntest # 80% PI for prop of left out obs in one bin of PIT values with range of p 
qbinom(c(0.25, 0.75), size = ntest, prob = p)/ntest # 50% PI for prop of left out obs in one bin of PIT values with range of p 

# coverage follows from pit
mean(pit.j < 0.025) # % below 95% PI
mean(pit.j < 0.05) # % below 90% PI
mean(pit.j < 0.1)
mean(pit.j > 0.975) # % above 95% PI 
mean(pit.j > 0.95) 
mean(pit.j > 0.9)
```


